# Generated by Django 3.2.4 on 2021-06-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delevery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название подразделения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название позиции доставки')),
                ('count', models.FloatField(verbose_name='Количество позиции доставки')),
                ('delevery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deleveris', to='logistics.delevery')),
                ('unit_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units_organization', to='logistics.delevery')),
            ],
        ),
        migrations.AddField(
            model_name='delevery',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_unit', to='logistics.unitorganization', verbose_name='Пункт доставки'),
        ),
        migrations.AddField(
            model_name='delevery',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_unit', to='logistics.unitorganization', verbose_name='Пункт отправки'),
        ),
    ]
