# Generated by Django 3.2.4 on 2021-07-05 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delevery',
            options={'verbose_name': 'Доставка', 'verbose_name_plural': 'Доставки'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Торговая позиция', 'verbose_name_plural': 'Торговые позиции'},
        ),
        migrations.AlterModelOptions(
            name='unitorganization',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterField(
            model_name='product',
            name='delevery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='logistics.delevery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='logistics.unitorganization'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_organizations', models.ManyToManyField(related_name='profiles_staff', to='logistics.UnitOrganization', verbose_name='Профили сотрудников')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
            },
        ),
    ]
