# Generated by Django 3.2.4 on 2021-07-06 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_auto_20210705_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('head_of_pharmacy', 'Head_of_pharmacy'), ('admin', 'Admin')], default='STAFF', max_length=20),
        ),
        migrations.CreateModel(
            name='TabelUchetaRabochegoVremeniT12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabel_ucheta_rabochego_vremeni_t12', to='logistics.unitorganization')),
            ],
            options={
                'verbose_name': 'Таблица учёта рабочего времени',
                'verbose_name_plural': 'Таблицы учёта рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='RowOfTabelUchetaRabochegoVremeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='row_table_ucheta_rabochego_vremeni', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='logistics.tabeluchetarabochegovremenit12')),
            ],
            options={
                'verbose_name': 'Строка таблицы учёта рабочего времени',
                'verbose_name_plural': 'СтрокИ таблицы учёта рабочего времени',
            },
        ),
    ]
