# Generated by Django 3.2.4 on 2021-07-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_auto_20210706_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rowoftabeluchetarabochegovremeni',
            options={'verbose_name': 'Строка таблицы учёта рабочего времени', 'verbose_name_plural': 'Строки таблицы учёта рабочего времени'},
        ),
    ]
