# Generated by Django 3.2.4 on 2021-07-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_rowoftabeluchetarabochegovremeni_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabeluchetarabochegovremenit12',
            name='unit_organization',
        ),
        migrations.DeleteModel(
            name='RowOfTabelUchetaRabochegoVremeni',
        ),
        migrations.DeleteModel(
            name='TabelUchetaRabochegoVremeniT12',
        ),
    ]
