# Generated by Django 3.2.4 on 2021-07-08 21:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day', models.DateField(default=datetime.date(2021, 7, 8), verbose_name='Первый день')),
                ('unit_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabel_ucheta_rabochego_vremeni_t12', to='logistics.unitorganization')),
            ],
            options={
                'verbose_name': 'Таблица учёта рабочего времени',
                'verbose_name_plural': 'Таблицы учёта рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='row_table_ucheta_rabochego_vremeni', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='employee_time_sheet.table')),
            ],
            options={
                'verbose_name': 'Строка таблицы учёта рабочего времени',
                'verbose_name_plural': 'Строки таблицы учёта рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, null=True, verbose_name='День')),
                ('status', models.CharField(blank=True, choices=[('came_to_work', 'Came_to_work'), ('no_came_to_work', 'no_came_to_work')], max_length=20, null=True)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='employee_time_sheet.row')),
            ],
        ),
    ]
