# Generated by Django 3.2.4 on 2021-07-06 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0005_auto_20210706_1946'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelUchetaRabochegoVremeniT12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabel_ucheta_rabochego_vremeni_t12', to='logistics.unitorganization')),
            ],
            options={
                'verbose_name': 'Таблица учёта рабочего времени',
                'verbose_name_plural': 'Таблицы учёта рабочего времени',
            },
        ),
        migrations.CreateModel(
            name='RowOfTabelUchetaRabochegoVremeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='row_table_ucheta_rabochego_vremeni', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='employee_time_sheet.tabeluchetarabochegovremenit12')),
            ],
            options={
                'verbose_name': 'Строка таблицы учёта рабочего времени',
                'verbose_name_plural': 'Строки таблицы учёта рабочего времени',
            },
        ),
    ]
