# Generated by Django 3.2.4 on 2021-07-10 11:24

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0002_alter_unitorganization_slug'),
        ('employee_time_sheet', '0002_alter_table_first_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='table',
            name='year',
            field=models.IntegerField(default=2021),
        ),
        migrations.AlterField(
            model_name='day',
            name='status',
            field=models.CharField(blank=True, choices=[('came_to_work', 'Came_to_work'), ('no_came_to_work', 'no_came_to_work'), ('not_info', 'not_info')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='first_day',
            field=models.DateField(default=datetime.datetime(2021, 7, 10, 0, 0), verbose_name='Первый день'),
        ),
        migrations.AlterUniqueTogether(
            name='row',
            unique_together={('staff', 'table')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('unit_organization', 'year', 'month')},
        ),
    ]
