# Generated by Django 3.2.4 on 2021-07-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_time_sheet', '0003_auto_20210710_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='first_day',
            field=models.DateField(blank=True, null=True, verbose_name='Первый день'),
        ),
    ]
